import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoIcon } from "@/assets/logo-icon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center pl-4 items-center z-20 top-0 h-20 bg-white">
          <div className="flex text-3xl font-bold flex-row items-center">
            <LogoIcon width={42} height={42} />
            <span className="text-[#FF6D33] ml-1">Prop</span>
            <span className="text-black ml-px">soch</span>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
