import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LogoIcon } from "@/assets/logo-icon";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center items-center px-6 z-20 top-0 h-20 bg-white shadow-sm border-b border-gray-200 sticky">
          <div className="flex flex-col md:flex-row items-center gap-1 md:gap-4">
            <div className="flex items-center">
              <LogoIcon width={42} height={42} />
              <h1 className="flex items-baseline ml-2 font-extrabold text-3xl select-none">
                <span className="text-[#FF6D33]">Prop</span>
                <span className="text-black ml-px">soch</span>
              </h1>
            </div>
            <p className="hidden md:block text-sm text-gray-600 font-medium select-none mt-0.5">
              A guided home buying program
            </p>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
